proxy:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./proxy/:/etc/nginx/conf.d/
  links:
    - server-a
    - server-b
    - server-c

server-a:
  build: ./server
  volumes:
    - ./server:/app
  links:
    - db
    
server-b:
  build: ./server
  volumes:
    - ./server:/app
  links:
    - db

server-c:
  build: ./server
  volumes:
    - ./server:/app
  links:
    - db

db:
  image: redis
  hostname: redis
  ports:
    - "6379:6379"